// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PresTech.Data;

#nullable disable

namespace PresTechBackEnd.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123063015_ElimineTablaX")]
    partial class ElimineTablaX
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PresTechBackEnd.Models.OfertaPrestamo", b =>
                {
                    b.Property<int>("OfertaPrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfertaPrestamoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cuotas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disponible")
                        .HasColumnType("bit");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Interes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrestamistaId")
                        .HasColumnType("int");

                    b.HasKey("OfertaPrestamoId");

                    b.HasIndex("PrestamistaId");

                    b.ToTable("OfertasPrestamo");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"));

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumentoID")
                        .HasColumnType("int");

                    b.HasKey("PersonaId");

                    b.HasIndex("TipoDocumentoID");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestamista", b =>
                {
                    b.Property<int>("PrestamistaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamistaId"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("PrestamistaId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Prestamistas");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int>("CuotasRestantes")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaProxPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("OfertaPrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("PrestatarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoPrestamo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaldoRestante")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PrestamoId");

                    b.HasIndex("OfertaPrestamoId");

                    b.HasIndex("PrestatarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestatario", b =>
                {
                    b.Property<int>("PrestatarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestatarioId"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("PrestatarioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("Prestatarios");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TipoDocumentos");

                    b.HasData(
                        new
                        {
                            TipoDocumentoId = 1,
                            Nombre = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            TipoDocumentoId = 2,
                            Nombre = "Cédula de Extranjería"
                        },
                        new
                        {
                            TipoDocumentoId = 3,
                            Nombre = "Pasaporte"
                        });
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Transaccion", b =>
                {
                    b.Property<int>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaccionId"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoTransaccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransaccionId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.OfertaPrestamo", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.Prestamista", "Prestamista")
                        .WithMany()
                        .HasForeignKey("PrestamistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamista");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Persona", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestamista", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestamo", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.OfertaPrestamo", "OfertaPrestamo")
                        .WithMany("Prestamos")
                        .HasForeignKey("OfertaPrestamoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PresTechBackEnd.Models.Prestatario", "Prestatario")
                        .WithMany("Prestamos")
                        .HasForeignKey("PrestatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfertaPrestamo");

                    b.Navigation("Prestatario");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestatario", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Transaccion", b =>
                {
                    b.HasOne("PresTechBackEnd.Models.Prestamo", "Prestamo")
                        .WithMany("Transacciones")
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.OfertaPrestamo", b =>
                {
                    b.Navigation("Prestamos");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestamo", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("PresTechBackEnd.Models.Prestatario", b =>
                {
                    b.Navigation("Prestamos");
                });
#pragma warning restore 612, 618
        }
    }
}
